$(document).ready(function() {

	// Get languages
	var languageIndices = [];
	$('tbody tr').each(function(index, tr){
		// Language row
		if (index == 0) {
			$('td', tr).each(function (index2, td){
				var language = $(td).text();
				if (language.length > 0) {
					if (language.substring(0, 2) != '//') {
						languageIndices[language] = index2;
						console.log('Added language ' + language + ' as index ' + index2);
					}
				}
			});
		}
	});

	// Add HTML to top of page
	$('body').prepend(
		'<div id="Converter" style="padding:20px">' +
			'Select a language to convert: ' +
			'<select>' +
				GetOptions() +
			'</select> ' +
			'<button>Convert</button>' +
		"</div>"
	);

	// Populate the select list
	function GetOptions () {
		var options = '';
		//for (var i = 0; i < languageIndices.length; i++) {
		for (var key in languageIndices) {
			options += '<option value="' + key + '">' + key + '</option>';
		}
		return options;
	}

	// Do conversion. Create both JSON and LanguageData.cs C# code.
	$('button').click(function(){
		var tab = '	';
		var columnNumber = languageIndices[$('select').val()];

		var autoGenComment = '// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.\n\n';

		var json = '{\n';
		json += tab + autoGenComment;
		json += tab + '// ' + $('select').val() + '\n\n';

		var cSharp = autoGenComment;
		cSharp += 'using UnityEngine;\n\n';
		cSharp += 'namespace TallowmereII {\n\n';
		cSharp += tab + '[System.Serializable]\n';
		cSharp += tab + 'public class LanguageData {\n\n';

		$('tr').each(function(index, tr){
			var firstColumnString = $('td', tr).eq(0).text();
			
			if (firstColumnString.length > 0) {
				// Is this a comment?
				if (firstColumnString.substring(0, 2) == "//") {
					json += tab + firstColumnString + '\n';

					var headerString = firstColumnString.substring(3);
					if (headerString != "String IDs") {
						cSharp += tab + tab + '[Header("' + headerString + '")]\n';
					}
				}
				// This is a key
				else {
					var keyString = firstColumnString;
					var valueString = $('td', tr).eq(columnNumber).text();
					json += tab + '"' + keyString + '": "' + valueString + '",\n';

					cSharp += tab + tab + 'public string ' + keyString + ';\n';
				}
			}
			else {
				json += '\n';
				cSharp += '\n';
			}
		});

		// Remove trailing comma and newline
		json = json.substring(0, json.length-2) + '\n';

		json += '}\n';

		cSharp += tab + '}\n\n';
		cSharp += '}\n';

		$('#Converter').append(
			'<br /><br /><b>Here is your JSON:</b> <br />' +
			'<textarea style="width:80%; height:40%"">' + json + '</textarea>' +
			'<br /><br />' +
			'<b>Here is your LanguageData.cs:</b> <br />' +
			'<textarea style="width:80%; height:40%"">' + cSharp + '</textarea>'
		);
	});

});